Run tests/checks without UV and ignore failure of the Nix build until we can fix it (#58)
After running `nix flake update`, `nix develop` gives:

```
warning: Git tree '/home/niklas/git/nyl' is dirty
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/xb4yfxa32hsjpincdgjv7xdq9kyys8l9-source/pkgs/stdenv/generic/make-derivation.nix:375:7

       … while evaluating attribute 'buildInputs' of derivation 'nix-shell'
         at /nix/store/xb4yfxa32hsjpincdgjv7xdq9kyys8l9-source/pkgs/stdenv/generic/make-derivation.nix:422:7:
          421|       depsHostHost                = elemAt (elemAt dependencies 1) 0;
          422|       buildInputs                 = elemAt (elemAt dependencies 1) 1;
             |       ^
          423|       depsTargetTarget            = elemAt (elemAt dependencies 2) 0;

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'hatchling' missing
       at /nix/store/71i8gf2xb1x1hzlc99djr94l2zh7jh5v-source/build/lib/resolvers.nix:32:17:
           31|         let
           32|           pkg = set.${name};
             |                 ^
           33|           dependencies = pkg.passthru.dependencies or { };
```

And we need to update it to get a later version of Kyverno because
96f2614 started to require Kyverno 1.13.x.

This MR adds another CI job that runs the Python checks and tests
directly with UV and without Nix, and allows the Nix build to fail
(GitHub doesn't seem to have a `allow_failure` option for its CI, so we
need to `|| true` the run commands).